"use client"

import { useState, useCallback, useEffect, useRef } from "react"
import { Sparkles, Loader2, Check, Bookmark } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { patchProject, type Project, type AiSuggestions } from "@/lib/projects"

const DURATION_OPTIONS = [
  { value: "10", label: "10 min" },
  { value: "20", label: "20 min" },
  { value: "30", label: "30 min" },
  { value: "45", label: "45 min" },
]

function relativeTime(isoString: string): string {
  const diff = Date.now() - new Date(isoString).getTime()
  const minutes = Math.floor(diff / 60_000)
  const hours = Math.floor(minutes / 60)
  const days = Math.floor(hours / 24)
  if (days > 0) return `${days} day${days > 1 ? "s" : ""} ago`
  if (hours > 0) return `${hours} hour${hours > 1 ? "s" : ""} ago`
  if (minutes > 0) return `${minutes} min ago`
  return "just now"
}

export function SuggestionsTab({ project, onUpdate }: { project: Project; onUpdate: () => void }) {
  const [suggestions, setSuggestions] = useState<Partial<AiSuggestions> | null>(
    project.aiSuggestions ?? null
  )
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [duration, setDuration] = useState(project.targetDuration?.toString() ?? "20")
  const hasAutoGenerated = useRef(false)

  useEffect(() => {
    setSuggestions(project.aiSuggestions ?? null)
    setDuration(project.targetDuration?.toString() ?? "20")
  }, [project.id, project.aiSuggestions, project.targetDuration])

  function handleDurationChange(val: string | null) {
    if (!val) return
    setDuration(val)
    patchProject(project.id, { targetDuration: parseInt(val) }).then(onUpdate)
  }

  const generate = useCallback(async () => {
    setLoading(true)
    setError(null)
    setSuggestions({})

    try {
      const res = await fetch("/api/ai/suggestions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: project.topic,
          description: project.description,
          duration: parseInt(duration),
        }),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error ?? "Unknown error")
      }

      const reader = res.body?.getReader()
      if (!reader) throw new Error("No stream available")

      const decoder = new TextDecoder()
      let accumulated = ""

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        accumulated += decoder.decode(value, { stream: true })
        try {
          setSuggestions(JSON.parse(accumulated))
        } catch {
          // Still streaming
        }
      }

      const final: AiSuggestions = JSON.parse(accumulated)
      const withMeta: AiSuggestions = {
        ...final,
        generatedAt: new Date().toISOString(),
        savedConcepts: project.aiSuggestions?.savedConcepts ?? [],
      }
      setSuggestions(withMeta)
      await patchProject(project.id, { aiSuggestions: withMeta })
      onUpdate()
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong")
    } finally {
      setLoading(false)
    }
  }, [project, duration, onUpdate])

  // Auto-generate on first visit when no suggestions exist
  useEffect(() => {
    if (hasAutoGenerated.current) return
    if (!project.aiSuggestions && project.topic) {
      hasAutoGenerated.current = true
      generate()
    }
  }, [project.id, project.topic, project.aiSuggestions, generate])

  function handleChooseTitle(title: string) {
    const next = project.chosenTitle === title ? undefined : title
    patchProject(project.id, { chosenTitle: next }).then(onUpdate)
  }

  function handleToggleConcept(concept: string) {
    const prev = suggestions?.savedConcepts ?? []
    const next = prev.includes(concept)
      ? prev.filter((c) => c !== concept)
      : [...prev, concept]
    const updated = { ...suggestions, savedConcepts: next } as AiSuggestions
    setSuggestions(updated)
    patchProject(project.id, { aiSuggestions: updated })
  }

  const savedConcepts = suggestions?.savedConcepts ?? []
  const hasTitles = (suggestions?.titles?.length ?? 0) > 0
  const hasHooks = (suggestions?.hookVariants?.length ?? 0) > 0
  const hasOutline = (suggestions?.scriptOutline?.length ?? 0) > 0
  const hasChapters = (suggestions?.chapterMarkers?.length ?? 0) > 0
  const hasThumbnails = (suggestions?.thumbnailConcepts?.length ?? 0) > 0
  const hasAnything = hasTitles || hasHooks || hasOutline || hasChapters || hasThumbnails

  if (error && !hasAnything) {
    return (
      <div className="py-12 text-center">
        <p className="text-destructive font-medium">{error}</p>
        <Button variant="outline" className="mt-4" onClick={generate}>Try again</Button>
      </div>
    )
  }

  if (!hasAnything && !loading) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center">
        <Sparkles className="mb-3 h-10 w-10 text-muted-foreground/40" />
        <p className="font-medium">Generate AI suggestions</p>
        <p className="mt-1 text-sm text-muted-foreground max-w-sm">
          Get title ideas, thumbnail concepts, hook variants, and a longform script outline.
        </p>
        <div className="mt-4 flex items-center gap-3">
          <Select value={duration} onValueChange={handleDurationChange}>
            <SelectTrigger className="w-32">
              <SelectValue placeholder="Duration" />
            </SelectTrigger>
            <SelectContent>
              {DURATION_OPTIONS.map((o) => (
                <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button onClick={generate}>
            <Sparkles className="mr-2 h-4 w-4" />
            Generate
          </Button>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <Select value={duration} onValueChange={handleDurationChange}>
          <SelectTrigger className="w-28 h-8 text-sm">
            <SelectValue placeholder="Duration" />
          </SelectTrigger>
          <SelectContent>
            {DURATION_OPTIONS.map((o) => (
              <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <div className="flex items-center gap-3">
          {suggestions?.generatedAt && (
            <p className="text-xs text-muted-foreground">
              Generated {relativeTime(suggestions.generatedAt)}
            </p>
          )}
          {loading ? (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Generating…
            </div>
          ) : (
            <Button variant="outline" size="sm" onClick={generate}>
              <Sparkles className="mr-2 h-3.5 w-3.5" />
              Regenerate
            </Button>
          )}
        </div>
      </div>

      {/* Titles */}
      {hasTitles && (
        <section className="space-y-3">
          <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground">Titles</h3>
          <div className="space-y-2">
            {suggestions?.titles?.map((title, i) => {
              const chosen = project.chosenTitle === title
              return (
                <Card key={i} className={chosen ? "border-primary/40 bg-primary/5" : ""}>
                  <CardContent className="flex items-center justify-between gap-4 p-3">
                    <p className="text-sm flex-1">{title}</p>
                    <div className="flex items-center gap-2 shrink-0">
                      <Badge variant="outline" className="text-xs">{i + 1}</Badge>
                      <Button
                        size="icon" variant={chosen ? "default" : "ghost"} className="h-7 w-7"
                        title={chosen ? "Deselect title" : "Use as video title"}
                        onClick={() => handleChooseTitle(title)}
                      >
                        <Check className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )
            })}
          </div>
        </section>
      )}

      {/* Hook Variants */}
      {hasHooks && (
        <section className="space-y-3">
          <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground">Hook Variants</h3>
          <div className="space-y-2">
            {suggestions?.hookVariants?.map((hook, i) => {
              const labels = ["Story", "Statistic", "Controversy"]
              return (
                <Card key={i}>
                  <CardContent className="p-3 space-y-1">
                    <Badge variant="outline" className="text-xs">{labels[i] ?? `Hook ${i + 1}`}</Badge>
                    <p className="text-sm mt-1">{hook}</p>
                  </CardContent>
                </Card>
              )
            })}
          </div>
        </section>
      )}

      {/* Script Outline */}
      {hasOutline && (
        <section className="space-y-3">
          <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground">Script Outline</h3>
          <div className="space-y-1.5">
            {suggestions?.scriptOutline?.map((section, i) => (
              <div key={i} className="flex gap-3 rounded-md border px-3 py-2.5">
                <span className="shrink-0 text-xs font-mono text-muted-foreground mt-0.5">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <p className="text-sm">{section}</p>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Chapter Markers */}
      {hasChapters && (
        <section className="space-y-3">
          <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground">Chapter Markers</h3>
          <Card>
            <CardContent className="p-3">
              <div className="space-y-1">
                {suggestions?.chapterMarkers?.map((chapter, i) => (
                  <p key={i} className="text-sm font-mono">{chapter}</p>
                ))}
              </div>
            </CardContent>
          </Card>
        </section>
      )}

      {/* Thumbnail Concepts */}
      {hasThumbnails && (
        <section className="space-y-3">
          <h3 className="font-semibold text-sm uppercase tracking-wide text-muted-foreground">Thumbnail Concepts</h3>

          {savedConcepts.length > 0 && (
            <div className="space-y-2 mb-1">
              <p className="text-xs text-muted-foreground font-medium">Saved</p>
              {savedConcepts.map((concept, i) => (
                <Card key={`saved-${i}`} className="border-primary/30 bg-primary/5">
                  <CardContent className="flex items-start justify-between gap-3 p-3">
                    <p className="text-sm flex-1">{concept}</p>
                    <Button
                      size="icon" variant="ghost" className="h-7 w-7 shrink-0 text-primary"
                      title="Unsave concept"
                      onClick={() => handleToggleConcept(concept)}
                    >
                      <Bookmark className="h-3.5 w-3.5 fill-current" />
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}

          <div className="space-y-2">
            {suggestions?.thumbnailConcepts?.map((concept, i) => {
              const pinned = savedConcepts.includes(concept)
              return (
                <Card key={i} className={pinned ? "opacity-60" : ""}>
                  <CardContent className="flex items-start justify-between gap-3 p-3">
                    <p className="text-sm flex-1">{concept}</p>
                    <Button
                      size="icon" variant="ghost"
                      className={["h-7 w-7 shrink-0", pinned ? "text-primary" : "text-muted-foreground"].join(" ")}
                      title={pinned ? "Unsave concept" : "Save concept"}
                      onClick={() => handleToggleConcept(concept)}
                    >
                      <Bookmark className={["h-3.5 w-3.5", pinned ? "fill-current" : ""].join(" ")} />
                    </Button>
                  </CardContent>
                </Card>
              )
            })}
          </div>
        </section>
      )}
    </div>
  )
}
